name: CI Zona Fit Evolution

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  validar-contenedores:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir Frontend
        run: docker build -t frontend-test .

      - name: Construir Backend
        run: docker build -t backend-test ./Backend

      - name: Verificar docker-compose
        run: docker compose config